## Testing Library Code

- Data Load
- Data Clean for clustering - Return information on what features can be used for what type clustering
 - 
  --- IE : col1-col3 : type decimal type integer col4-col5 : text 
- Run Random Clustering Techniques With Params


## Cleanup - generic



In [1]:
!pip3 install numpy


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numbers
import pandas as pd
import numpy as np



def find_null_columns(df):
    
    null_cols = []
    
    return null_cols



def check_type_numeric(col, df):
    if isinstance(df[col].idx[0], numbers.Number):
        return True
    else:
        return False
        


def find_null_indexes(series):
    
    idx_list = []
    
    return idx_list


def check_categories_by_threshold(df, col, threshold):
    
    if df[col].unique() <= threshold:
        return True
    else:
        return False

# def reorganise_features(df):
#     df = 


def __col_clean(df, cols, cat_threshold):
    
    nrows = df.shape[0]
    
    for col in cols:
        numeric = []
        strings = []
        dummies = []
        if check_type_numeric(col, df):
            df[col].fillna(df[col].mean())
            numeric.append(col)
        else:
            df = df[df[col] != np.nan | df[col] != None | df[col] != np.NaN]
            if check_categories_by_threshold(df, col, cat_threshold):
                dummies.append(col)
                df = pd.get_dummies(df, columns=[col, ])
                for cola in df.columns:
                    if col + '_value' in cola:
                        numeric.append(col)
            else:
                strings.append(col)
                df[col] = df[col].str.lower()
                              
    dropped_rows = nrows -  df.shape[0]
    
    return (df, {
        "numeric_columns" : numeric.length(),
        "string_columns" : strings.length(),
        "dropped_rows" : dropped_rows,
        "dummy_columns" : dummies,
        "n_rows" : nrows
        })
    
    

def quick_clean(df, cat_threshold=3):
    
    cols = df.columns
   
    cleaned = __col_clean(df, cols, cat_threshold)
    
    
    return cleaned

In [ ]:
def quick_clean_time_series(df, ts_columns, cat_threshold=3):
    '''
    Take input columns for time series, cleans other features and the time series data itself.
    ts_columns = time series columns 
        Ordered - largest interval,..., smallest interval
         if incorrectly ordered you will get strange behaviour
    cat_threshold = category threshold for one-hot encoding
     
    '''
    cols = df.columns
    
    for col in ts_columns:
        cols.remove(col)
        
    nrows = df.shape[0]
    
    cols = df.columns
    
    ## apply time series transforms
   ## apply dataframe transformations based on time-series analysis
   # windowing etc.
   # clearing missing steps or adding in gap information
   
   
    cleaned = __col_clean(df, cols, cat_threshold)
    
    
    return cleaned
    
    

In [2]:
import numpy as np


num_list = []


for x in range(1, 10):
    print(x)
    

# array = np.array([range])

1
2
3
4
5
6
7
8
9


In [4]:
matrix_1 = np.random.rand(3,3)
matrix_2 = np.random.rand(3,3)

print(matrix_1)
print(matrix_2)


[[0.19571635 0.15762506 0.89948332]
 [0.33897774 0.82040522 0.08151999]
 [0.1904581  0.55322632 0.51539453]]
[[0.52690453 0.10873711 0.92429976]
 [0.68741184 0.11959172 0.22976755]
 [0.4206532  0.95321077 0.67815   ]]


In [5]:
matrix_1

array([[0.5898477 , 0.89752948, 0.82710232],
       [0.77685682, 0.21267887, 0.55710232],
       [0.69744991, 0.57815076, 0.65266863]])

In [8]:
matrix_1[1, ]

array([0.33897774, 0.82040522, 0.08151999])

In [9]:
np.linalg.norm(matrix_1[1, ] - matrix_2[1, ] )

0.7965696622887207

In [14]:
# matrix_1 = np.random.rand(3,3)
matrix_test = np.random.rand(10,3)
matrix_test

array([[0.92235864, 0.35251013, 0.0028317 ],
       [0.34722867, 0.35341757, 0.87326568],
       [0.04948275, 0.35875927, 0.81793841],
       [0.69056471, 0.14068737, 0.84144052],
       [0.94390459, 0.42321022, 0.51833565],
       [0.9408061 , 0.93550344, 0.67700332],
       [0.53811337, 0.2598095 , 0.55458422],
       [0.07009078, 0.35664323, 0.48589277],
       [0.20866642, 0.70794755, 0.7918407 ],
       [0.91615151, 0.63285282, 0.01041247]])

In [15]:
len(matrix_test)

10

In [60]:

def compute_euc_distances_return_array(dataset):
    '''
    Returns a matrix of euclidean distances for row by row in a given dataset.
    Return rows = (n rows) columns = ( n rows)
    '''
    indexes = []
    
    
    
    for x in range(0, len(dataset)-1):
        index_maps = np.zeros( len(dataset))
        for y in range(0, len(dataset)-1):      
            if x!=y:
                index_maps[y] =  np.linalg.norm(dataset[x, ] - dataset[y, ] )
        
        indexes.append(index_maps)

    return np.array(indexes)


def find_nearest(dataset: np.ndarray) -> np.ndarray:
    '''
    Finds nearest euclidean partner withing a dataset of n rows.
    
    ----------------
    
    dataset : np.ndarray
    
    ---------------
    
    return : np.ndarray
            Array returned with euclidean distances row by row row index = from and column index = row to
    
    '''
    indexes = []
    
    for x in range(0, len(dataset)-1):
        index = 0
        distance = 999999999.99999
        for y in range(0, len(dataset)-1):
            if y==0:
                distance = np.linalg.norm(dataset[x, ] - dataset[y, ] )    
            if x!=y and np.linalg.norm(dataset[x, ] - dataset[y, ]) < distance:
                distance =  np.linalg.norm(dataset[x, ] - dataset[y, ] )
                index = y
        indexes.append([index, distance])

    return np.array(indexes)
    

# do some stuff with basic stats, what rows are most frequently the closest etc... 
# add in options for distance metrics - cosine, manhattan etc. taking a different approach from node based or clustering, maybe identify opportunites for cluster nodes with chunking and
# running this ie using a statistical sample and identifying proximity over small clumps


In [65]:
type(test)

numpy.ndarray

In [64]:
test = find_nearest(matrix_test)
# np.matrix(test)


array([8.        , 0.15131594])

In [24]:
matrix_test = np.random.rand(50,3)


test = compute_euc_distances_return_vector(matrix_test)


In [25]:
test

[[[0, 1], 0.5465101291749608],
 [[0, 2], 1.061123153021767],
 [[0, 3], 0.23284044171259047],
 [[0, 4], 1.022310990567531],
 [[0, 5], 0.971322671890359],
 [[0, 6], 0.9305104461384556],
 [[0, 7], 0.8605157380345051],
 [[0, 8], 0.15920534983996712],
 [[0, 9], 0.9509393396420209],
 [[0, 10], 0.2883543155469689],
 [[0, 11], 0.954825790356502],
 [[0, 12], 0.5538595796631821],
 [[0, 13], 0.6331228926123974],
 [[0, 14], 1.0213130231112486],
 [[0, 15], 0.9489516147233082],
 [[0, 16], 0.8355549305601584],
 [[0, 17], 0.6766828612233493],
 [[0, 18], 0.9781194110975417],
 [[0, 19], 0.8675537237976906],
 [[0, 20], 0.6272284508178264],
 [[0, 21], 0.8043646464698928],
 [[0, 22], 0.993575157708797],
 [[0, 23], 1.2406709652193573],
 [[0, 24], 0.7775185973989324],
 [[0, 25], 1.1437653369064926],
 [[0, 26], 0.646715267527505],
 [[0, 27], 1.0047358632656247],
 [[0, 28], 0.9107660682019457],
 [[0, 29], 0.8471742662098555],
 [[0, 30], 0.985528493218751],
 [[0, 31], 0.24318792903084477],
 [[0, 32], 0.70086440